version: 0.2

phases:
  install:
    commands:
      # Instala a versão especificada do Terraform e o adiciona ao PATH
      - echo "Instalando Terraform v${TERRAFORM_VERSION}..."
      - wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_arm64.zip
      - unzip -q terraform_${TERRAFORM_VERSION}_linux_arm64.zip
      - mkdir -p bin
      - mv terraform bin/
      - export PATH="$CODEBUILD_SRC_DIR/bin:$PATH"
      - terraform --version
      - echo "Instalação do Terraform concluída."

  pre_build:
    commands:
      # Configura o backend do Terraform
      - export TF_STATE_BUCKET=${AWS_S3_BUCKET_TARGET_NAME_0}
      - export TF_LOCK_TABLE=${AWS_DYNAMODB_TABLE_TARGET_NAME_0}

      # Muda para o diretório de trabalho principal
      - cd ${CODEBUILD_SRC_DIR}/StandAlone

      # --- Bloco de Processamento de Fontes Secundárias (Correção Definitiva) ---
      - echo "Procurando e processando fontes secundárias..."
      - |
        if [ -n "$SECONDARY_SOURCE_IDENTIFIERS" ]; then
          echo "Identificadores de fontes secundárias encontrados: '${SECONDARY_SOURCE_IDENTIFIERS}'"
          for identifier in $SECONDARY_SOURCE_IDENTIFIERS; do
            # 1. Constrói o NOME da variável de ambiente que contém o caminho da fonte secundária
            SOURCE_PATH_VAR_NAME="CODEBUILD_SRC_DIR_$identifier"

            # 2. Usa a indireção do shell ('!') para obter o VALOR da variável cujo nome foi construído acima
            SOURCE_PATH="${!SOURCE_PATH_VAR_NAME}"
            
            # Constrói o diretório de destino que simula o 'git clone' local
            DEST_DIR="./$identifier"

            echo "Processando fonte '${identifier}'..."
            echo "  - Variável de ambiente do caminho: ${SOURCE_PATH_VAR_NAME}"
            echo "  - Caminho da fonte resolvido: ${SOURCE_PATH}"
            echo "  - Diretório de destino: ${DEST_DIR}"

            if [ -d "$SOURCE_PATH" ]; then
              # Cria o diretório de destino (ex: ./LambdaDeploy)
              mkdir -p "${DEST_DIR}"
              
              # Copia o conteúdo da fonte baixada para dentro do diretório de destino
              cp -a ${SOURCE_PATH}/. "${DEST_DIR}/"
              echo "  - SUCESSO: Arquivos copiados."
            else
              echo "  - AVISO: Diretório da fonte ${SOURCE_PATH} não encontrado. Pulando."
            fi
          done
        else
          echo "Nenhuma fonte secundária para processar."
        fi
      - echo "Processamento de fontes secundárias concluído."
      # --- Fim do Bloco Corrigido ---

      # Baixa a configuração principal do Terraform
      - echo "Baixando configuração principal de s3://${TF_STATE_BUCKET}/states/${STATE_NAME}/main.tf"
      - aws s3 cp "s3://${TF_STATE_BUCKET}/states/${STATE_NAME}/main.tf" .

      # Inicializa o Terraform
      - echo "Inicializando o Terraform..."
      - |
        terraform init -reconfigure -no-color \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=states/${STATE_NAME}/terraform.tfstate" \
          -backend-config="region=${REGION}" \
          -backend-config="dynamodb_table=${TF_LOCK_TABLE}"

  build:
    commands:
      # Executa o comando Terraform
      - |
        set -e
        echo "Executando terraform ${COMMAND}..."
        if [ "${COMMAND}" = "plan" ]; then
          terraform plan -no-color
        elif [ "${COMMAND}" = "apply" ]; then
          terraform apply -auto-approve -no-color
        elif [ "${COMMAND}" = "destroy" ]; then
          terraform destroy -auto-approve -no-color
        else
          echo "ERRO: Comando desconhecido '${COMMAND}'. Use 'plan', 'apply' ou 'destroy'."
          exit 1
        fi

  post_build:
    commands:
      - echo "Processo do CodeBuild finalizado."
